# Generated by Django 4.1.7 on 2023-04-29 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('category', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('venue', models.CharField(max_length=300, null=True)),
                ('entryprice', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'OwnerEvent_table',
            },
        ),
    ]
