# Generated by Django 4.1.7 on 2023-05-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBS', '0002_ownerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerevent',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
